### ISSUE TITLE
The SDK is not compatible with app targetting Android 12

### ISSUE THREAD

**Issue by LivioGama** [SchweizerischeBundesbahnen/SwissPassSDK-Android#4]
Targeting S+ (version 10000 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent

https://stackoverflow.com/questions/68228666/targeting-s-version-10000-and-above-requires-that-one-of-flag-immutable-or-fl

WorkManager Version 2.6.0 is not compatible for apps targeting Android 12 (S). You should be using version 2.7.0 instead. Source: https://developer.android.com/jetpack/androidx/releases/work#version_260_3

Apparently you still use version 2.5.0

![CleanShot 2021-11-05 at 20 58 55](https://user-images.githubusercontent.com/6930498/140571706-bdcfab72-a48e-49da-b45e-4fa752318417.png)

**Comment by probert73** [comment]
Thanks, this issue will be fixed in the upcoming hotfix release 3.1.3

BTW in the future please submit bug reports through the official NOVA channel.

Thanks
--Philippe
