### ISSUE TITLE
Link Card Swisspass page feature doesn't bring back to application

### ISSUE THREAD

**Issue by ivancousillasmnc** [SchweizerischeBundesbahnen/SwissPassSDK-Android#5]
Hello,

I’m implementing the SwissPass link card management process using your SDK: `swissPassLoginClient.openSwissPass(Page.LINK_CARD_MANAGEMENT`  
which is a redirection to a web page. When using it, I get this:
![image](https://user-images.githubusercontent.com/95617918/148891786-595c75bc-74ea-460d-9517-fd9c486a4964.png)

When I click on _Link Now_, I guess the process should be done on SBB side and I should get the result of it. Unfortunately, it seems nothing happens.
I tried your demoApp and got the same result.
Am I missing something?

Thank you for your help!

**Comment by probert73** [comment]
In the future, please send bug reports via the NOVA User Group.

This might be a data issue, what CKM are you using for linking, is it from a PROD or INTE user/card?
