### ISSUE TITLE
Unable to resolve ch.sbb.sid.android.lib:swisspass:4.3.2 dependency for demoapp

### ISSUE THREAD

**Issue by gtomek** [SchweizerischeBundesbahnen/SwissPassSDK-Android#9]
After checking out the code, it is currently impossible to resolve `ch.sbb.sid.android.lib:swisspass:4.3.2` dependency

The following exception is thrown during the build:

```
> Could not resolve all files for configuration ':demoapp:debugRuntimeClasspath'.
   > Could not resolve ch.sbb.sid.android.lib:swisspass:4.3.2.
     Required by:
         project :demoapp
      > Could not resolve ch.sbb.sid.android.lib:swisspass:4.3.2.
         > Could not get resource 'https://sbb-artefact-repo-prod.s3.eu-central-1.amazonaws.com/releases/ch/sbb/sid/android/lib/swisspass/4.3.2/swisspass-4.3.2.pom'.
            > Could not GET 'https://sbb-artefact-repo-prod.s3.eu-central-1.amazonaws.com/releases/ch/sbb/sid/android/lib/swisspass/4.3.2/swisspass-4.3.2.pom'. Received status code 403 from server: Forbidden
```

The dependency mentioned in the  ReleaseNotes, i.e. `ch.sbb.sid.android.lib:swisspass-login:4.3.2` is not available either.

Only reverting the last change and targeting `'ch.sbb.sid.android.lib:swisspass-client:4.3.1'` dependency seems to work.

**Comment by mosberger** [comment]
Hi @gtomek 
Thanks for the heads up. It works now.
